name: procurap
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio: ^3.0.8
  flutter_mobx: ^1.1.0+2
  mobx: ^1.2.1+2
  flutter_modular: ^2.0.0+1

  datetime_picker_formfield: ^1.0.0
  mask_text_input_formatter: ^1.0.7
  flutter_masked_text: ^0.8.0
  intl: ^0.16.1

  shared_preferences: ^0.5.12+2



  # camera: #plugin da camera tá com defeito
  # path: 
  # path_provider: 
  image_picker: ^0.6.7+11
  photo_view: ^0.10.2 # para poder dar zomm na imagem só pegou em imagem local
  # pinch_zoom_image: ^0.2.5 # pega da internet ta



  cached_network_image: ^2.3.3








  flutter_localizations:
    sdk: flutter
  
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  mockito: ^4.1.1
  modular_codegen: ^2.0.0+1
  mobx_codegen: ^1.1.0+1
  build_runner: ^1.10.1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/fonts/Raleway-Regular.ttf
        - asset: fonts/fonts/Raleway-Italic.ttf
          # style: italic
    - family: Roboto
      fonts:
        - asset: fonts/fonts/Roboto-Regular.ttf
        - asset: fonts/fonts/Roboto-Bold.ttf
          # weight: 700
  
  uses-material-design: true

  #   - family: Trajan Prodata
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
vars: 
    clean: flutter clean
    get: flutter pub get
    runner: flutter pub run build_runner
scripts: 
    mobx_build: $runner build
    mobx_watch: $clean & $get & $runner watch
    mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs
