# Generated by Django 3.1.2 on 2020-10-22 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=4)),
                ('complemento', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=9)),
            ],
            options={
                'verbose_name': 'Endereco',
                'verbose_name_plural': 'Enderecos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('classificacao', models.CharField(blank=True, max_length=255)),
                ('num_banheiros', models.IntegerField(default='0')),
                ('num_conzinhas', models.IntegerField(default='0')),
                ('num_vagas', models.IntegerField(default='0')),
                ('num_quartos', models.IntegerField(default='0')),
                ('preco_imovel', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=9)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.endereco')),
            ],
            options={
                'verbose_name': 'Imovel',
                'verbose_name_plural': 'Imoveis',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoAnuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoContato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Email', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoImovel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoOspedagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9)),
                ('date_vencimento', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Imoveis', to='api.imovel')),
                ('tipo_ospedagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tipoospedagem')),
            ],
        ),
        migrations.AddField(
            model_name='imovel',
            name='tipo_anuncio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tipoanuncio'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='tipo_imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tipoimovel'),
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(blank=True, null=True, upload_to='imagens/imoveis')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.imovel')),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=255)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.imovel')),
                ('tipo_contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_contatos', to='api.tipocontato')),
            ],
        ),
    ]
