# Generated by Django 3.1.2 on 2020-10-20 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201020_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.imovel'),
        ),
        migrations.CreateModel(
            name='Imagens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_produto_b', models.ImageField(blank=True, null=True, upload_to='imagens/imoveis')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.imovel')),
            ],
        ),
    ]
