# Generated by Django 3.1.2 on 2020-10-22 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201022_1344'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoOspedagem',
            new_name='TipoHospedagem',
        ),
    ]
