# Generated by Django 3.1.2 on 2020-10-20 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201020_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagens',
            old_name='foto_produto_b',
            new_name='url',
        ),
    ]
