# Generated by Django 3.1.2 on 2020-10-20 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201020_1248'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imagens',
            new_name='Imagem',
        ),
    ]
