# Generated by Django 3.1.2 on 2020-10-20 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201020_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imovel',
            old_name='n_banheiros',
            new_name='num_banheiros',
        ),
        migrations.RenameField(
            model_name='imovel',
            old_name='n_conzinhas',
            new_name='num_conzinhas',
        ),
        migrations.RenameField(
            model_name='imovel',
            old_name='n_quartos',
            new_name='num_quartos',
        ),
        migrations.RenameField(
            model_name='imovel',
            old_name='n_vagas',
            new_name='num_vagas',
        ),
    ]
